// Actions
export const SIGNUP_ACTION = 'SIGNUP_ACTION';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const AUTO_LOGOUT_ACTION = 'AUTO_LOGOUT_ACTION';
export const AUTH_ACTION = 'AUTH_ACTION';
export const AUTO_LOGIN_ACTION = 'AUTO_LOGIN_ACTION';

// Mutations
export const SET_USER_TOKEN_DATA_MUTATION = 'SET_USER_TOKEN_DATA_MUTATION';
export const LOADING_SPINNER_SHOW_MUTATION = 'LOADING_SPINNER_SHOW_MUTATION';
export const SET_AUTO_LOGOUT_MUTATION = 'SET_AUTO_LOGOUT_MUTATION';

// Getters
export const GET_USER_TOKEN_GETTER = 'GET_USER_TOKEN_GETTER';
export const IS_USER_AUTHENTICATE_GETTER = 'IS_USER_AUTHENTICATE_GETTER';